package com.myspace.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class data implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DATA_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "DATA_ID_SEQ", name = "DATA_ID_GENERATOR")
    private java.lang.Long id;

    public data() {
    }
    
    public data(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}